name: ci

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: '**'
    paths:
      - 'src/**'
      - '.editorconfig'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            src
            .editorconfig

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: Restore the project dependencies.
        working-directory: src
        run: dotnet restore

      - name: Run the linter.
        working-directory: src
        run: dotnet format --no-restore --verify-no-changes --verbosity diagnostic


  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            src
            .editorconfig

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: Restore the project dependencies.
        working-directory: src
        run: dotnet restore

      - name: Build the source directory.
        working-directory: src
        run: dotnet build --no-restore --warnaserror --configuration ${{ matrix.configuration }} /p:ContinuousIntegrationBuild=true


  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            src
            .editorconfig

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: Restore the project dependencies.
        working-directory: src
        run: dotnet restore

      - name: Build the source directory.
        working-directory: src
        run: dotnet build --no-restore --configuration ${{ matrix.configuration }} /p:ContinuousIntegrationBuild=true

      - name: Run the tests.
        working-directory: src
        run: dotnet test --no-build --configuration ${{ matrix.configuration }} --warnaserror


  aot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            src
            .editorconfig

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: Restore the AOT project dependencies.
        working-directory: src
        run: dotnet restore --runtime linux-x64

      - name: Build the AOT project directory.
        working-directory: src/aot
        run: dotnet build --no-restore --configuration Release --runtime linux-x64 /p:ContinuousIntegrationBuild=true

      - name: Publish the AOT project.
        working-directory: src/aot
        run: dotnet publish --no-build --configuration Release --runtime linux-x64 --output "${{ runner.temp }}/aot_output"

      - name: Run the published AOT project.
        run: "${{ runner.temp }}/aot_output/AotCompatibility.TestApp"


  publish:
    # Ignore main and develop since they'll have separate publish workflows.
    if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            target-runtime: linux-x64

          - runner: ubuntu-24.04-arm
            target-runtime: linux-arm64

          - runner: windows-latest
            target-runtime: win-x64

          - runner: windows-11-arm
            target-runtime: win-arm64

          - runner: macos-latest
            target-runtime: osx-arm64

          - runner: macos-26-intel
            target-runtime: osx-x64

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            src
            .editorconfig

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: Restore the project dependencies.
        working-directory: src
        run: dotnet restore --runtime ${{ matrix.target-runtime }}

      - name: Build the project directory.
        working-directory: src/client
        run: dotnet build --no-restore --configuration Release --runtime ${{ matrix.target-runtime }} /p:ContinuousIntegrationBuild=true

      - name: Publish the project.
        working-directory: src/client
        run: dotnet publish --no-build --configuration Release --runtime ${{ matrix.target-runtime }} --output "${{ runner.temp }}/aot_output"
